name: pranomics_pipeline

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.10
  - pip

  # core bio tools
  - fastqc
  - bowtie2
  - samtools
  - stringtie
  - sra-tools
  - trimmomatic
  - r-base

  # R packages
  - bioconductor-edger
  - bioconductor-limma

  # pip packages
  - pip:
      - pandas
      - numpy
      - rich
      - plotly
      - matplotlib
      